### ISSUE TITLE
bluetooth is not working on a71

### ISSUE THREAD

**Issue by zainullahk** [ponces/treble_build_pe#11] opened 2021-12-21 16:55 UTC
## Build date

```
Pixel Experience 12.0 v400.d
```

## Expected Behavior

```
when connecting any bluetooth device it should connect with no issue
```

## Current Behavior

```
it says connecting and then throws me  back to the main bluetooth menu when i click connect then shows me  the mac addres of the device and then dissapaears and then the name of the bluetooth device appears and it repeats this whole thing over and over
```

## Possible Solution

```
Edit here
```

## Steps to Reproduce

```
1.
2.
3.
4.
```

Device: Samsung galaxy A71
GSI version: 12
Vendor version: 11

**Comment by ponces** [comment] 2021-12-21 19:38
Duplicate of phhusson/treble_experimentations#2117.
Issue closed.

**Closed by ponces** 2021-12-21 19:38 UTC

**Comment by zainullahk** [comment] 2021-12-22 12:09
i know its a duplicate but phusson has so many reports of bugs that mine being fixed is rare

**Comment by ponces** [comment] 2021-12-23 00:58
Why are you relying on others to fix your issues in the first place?
if you have any urgency on that, figure it out yourself!
